name: eicl_venv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - pip:
      - absl-py==1.2.0
      - dill==0.3.5.1
      - dm-haiku==0.0.9
      - jaxline==0.0.5
      - ml_collections==0.1.1
      - numpy==1.23.2
      - optax==0.1.3
      - tensorflow==2.9.1
      - tensorflow_datasets==4.6.0
